imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @AppBundle/Resources/config/parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: [en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Sonata configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

sonata_admin:
    title:      'Admin panel'
    title_logo: img/logo_small.png
    options:
        html5_validate:       true
        # Auto order groups and admins by label or id
        sort_admins:          false
        confirm_exit:         true
        use_select2:          true
        use_icheck:           true
        use_bootlint:         false
        use_stickyforms:      true
        form_type:            standard
        dropdown_number_groups_per_colums:  2
    
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
        knp_menu_template: SonataAdminBundle:Menu:sonata_menu.html.twig
        layout:  SonataAdminBundle::standard_layout.html.twig

    dashboard:
        blocks:
            # display two dashboard blocks
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [my_name1, my_name2] # or [Category, Posr]
            -
                position: right # top (show on top position)
                type: sonata.admin.block.admin_list
                settings:
                    groups: [my_name2]  # or [Post]

        groups:
            my_menu: # or - Category
                provider:        app.menu_builder
                icon:            '<i class="fa fa-edit"></i>'

            my_name1: # or - Category
                label:                ~
                label_catalogue:      ~
                items:
                    - admin.category
                    - route:        home
                      label:        Blog
                    - route:        test
                      route_params: { articleId: 3 }
                      label:        Article

            my_name2: # or - Post
                items:
                    - admin.blog.post
                    - admin.blog.post
                    - admin.blog.post
                    - admin.blog.post

            my_menu:

                items:
                    - admin.blog.post
                    - admin.blog.post
 
